"""add_spreadsheet_id_to_restaurants

Revision ID: 298e699b79b4
Revises: 7731956a9283
Create Date: 2026-02-02 09:20:04.044308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298e699b79b4'
down_revision: Union[str, None] = '7731956a9283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('spreadsheet_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'spreadsheet_id')
    # ### end Alembic commands ###
