"""add_package_fields_to_product

Revision ID: 7731956a9283
Revises: 3eeb68a1309b
Create Date: 2026-02-01 00:01:32.667255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7731956a9283'
down_revision: Union[str, None] = '3eeb68a1309b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('package_size', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('products', sa.Column('package_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'package_unit')
    op.drop_column('products', 'package_size')
    # ### end Alembic commands ###
