"""initial_schema

Revision ID: cc9ed7d0a628
Revises: 
Create Date: 2026-01-30 21:52:43.464805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9ed7d0a628'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iiko_id', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_vn', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_iiko_id'), 'products', ['iiko_id'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iiko_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time_zone', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iiko_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VERIFIED_BY_COOK', 'EXPORTED_TO_PROCOB', name='orderstatus'), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tech_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iiko_dish_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('COOK', 'MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('linked_restaurant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['linked_restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tech_cards')
    op.drop_table('stock_balances')
    op.drop_table('sales_plans')
    op.drop_table('orders')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_products_iiko_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
